/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CtrlCandidates;
import Controller.CtrlPeriods;
import Controller.CtrlUsers;
import java.awt.Color;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Eithel
 */
public class adminFrame extends javax.swing.JFrame {

    CtrlCandidates cc = new CtrlCandidates();
    CtrlUsers vt = new CtrlUsers();
    CtrlPeriods pr = new CtrlPeriods();

    /**
     * Creates new form adminFrame
     */
    public adminFrame() {
        initComponents();
        setLocationRelativeTo(null);
        listPeriods();
        this.listCandidates();
        this.listVoters();
        generateKey();
        this.pr.getActivePeriods(txtLimitDatePeriod);
    }

    public void listPeriods() {
        pr.loadDataPeriods(tblPeriods);
    }

    public void clearFiledsPeriods() {
        pr.addPeriod(txtStartDatePeriods, txtFinishDatePeriods, txtStatusPeriod);
    }

    public void listVoters() {
        vt.loadDataUsers(tblVoters);
    }

    public void clearFiledsVoters() {
        vt.clearFields(txtIdNumberVoter, txtNameVoter, txtAgeVoter, txtEmailVoter, txtTelephoneVoter, txtKey);
    }

    public void generateKey() {
        String randomKey = vt.generateRandomKey();
        txtKey.setText(randomKey);
    }

    public void listCandidates() {
        cc.loadDataCandidates(tblCandidate);
    }

    public void clearFiledsCandidates() {
        cc.clearFields(txtIdNumberCandidate, txtNameCandidate, txtPoliticParty, txtImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVoters = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        txtIdNumberVoter = new javax.swing.JTextField();
        lblIdentificación2 = new javax.swing.JLabel();
        txtNameVoter = new javax.swing.JTextField();
        lblNombre2 = new javax.swing.JLabel();
        txtEmailVoter = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtTelephoneVoter = new javax.swing.JTextField();
        lblRuta2 = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtAgeVoter = new javax.swing.JTextField();
        lblClave = new javax.swing.JLabel();
        txtKey = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        txtLimitDatePeriod = new javax.swing.JTextField();
        btnGenerateKey = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnAddVoter = new javax.swing.JButton();
        btnUpdateVoter = new javax.swing.JButton();
        btnDeleteVoter = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPeriods = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        txtStartDatePeriods = new javax.swing.JTextField();
        lblStart_date = new javax.swing.JLabel();
        txtFinishDatePeriods = new javax.swing.JTextField();
        lblFinish_date = new javax.swing.JLabel();
        txtStatusPeriod = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnAddPeriods = new javax.swing.JButton();
        btnUpdatePeriods = new javax.swing.JButton();
        btnDeletePeriods = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCandidate = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        lblIdentificación1 = new javax.swing.JLabel();
        txtIdNumberCandidate = new javax.swing.JTextField();
        txtNameCandidate = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        lblPartidoPolítico1 = new javax.swing.JLabel();
        txtPoliticParty = new javax.swing.JTextField();
        txtImage = new javax.swing.JTextField();
        lblRuta1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnAddCandidate = new javax.swing.JButton();
        btnUpdateCandidate = new javax.swing.JButton();
        btnDeleteCandidate = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        pnBtnExit = new javax.swing.JPanel();
        lblExit5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        tblVoters.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblVoters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Cedula", "Nombre", "Email", "Edad", "Teléfono", "Clave", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVoters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVotersMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblVoters);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Votantes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N

        lblIdentificación2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIdentificación2.setText("Cedula:");

        lblNombre2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNombre2.setText("Nombre:");

        lblEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEmail.setText("Correo Electronico:");

        lblRuta2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblRuta2.setText("Telefono:");

        lblAge.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblAge.setText("Edad:");

        lblClave.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblClave.setText("Clave:");

        txtKey.setEditable(false);
        txtKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeyActionPerformed(evt);
            }
        });

        lblFecha.setText("Periodo Para votar:");

        txtLimitDatePeriod.setEditable(false);
        txtLimitDatePeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLimitDatePeriodActionPerformed(evt);
            }
        });

        btnGenerateKey.setText("...");
        btnGenerateKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateKeyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblIdentificación2)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdNumberVoter, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFecha)
                            .addComponent(lblClave))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLimitDatePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblNombre2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNameVoter, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmailVoter, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblRuta2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTelephoneVoter, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblAge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAgeVoter, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGenerateKey)
                .addGap(40, 40, 40))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdNumberVoter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdentificación2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameVoter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre2))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmailVoter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelephoneVoter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRuta2))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAgeVoter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClave)
                    .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerateKey))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLimitDatePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        btnAddVoter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/AgregarUsuario.png"))); // NOI18N
        btnAddVoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVoterActionPerformed(evt);
            }
        });

        btnUpdateVoter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Editar.png"))); // NOI18N
        btnUpdateVoter.setMaximumSize(new java.awt.Dimension(72, 23));
        btnUpdateVoter.setMinimumSize(new java.awt.Dimension(72, 23));
        btnUpdateVoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateVoterActionPerformed(evt);
            }
        });

        btnDeleteVoter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Eliminar.png"))); // NOI18N
        btnDeleteVoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVoterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnAddVoter, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnUpdateVoter, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnDeleteVoter, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddVoter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateVoter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteVoter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar votantes", jPanel3);

        tblPeriods.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblPeriods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Fecha de inicio", "Fecha de finalización", "Estado"
            }
        ));
        tblPeriods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPeriodsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblPeriods);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Periodos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N

        lblStart_date.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblStart_date.setText("Fecha de inicio:");

        lblFinish_date.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblFinish_date.setText("Fecha de finalización:");

        lblStatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblStatus.setText("Estado:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFinish_date)
                    .addComponent(lblStart_date)
                    .addComponent(lblStatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStartDatePeriods, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFinishDatePeriods, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatusPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStartDatePeriods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStart_date))
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFinishDatePeriods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFinish_date))
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(txtStatusPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        btnAddPeriods.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/AgregarPeriodo.png"))); // NOI18N
        btnAddPeriods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPeriodsActionPerformed(evt);
            }
        });

        btnUpdatePeriods.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Editar.png"))); // NOI18N
        btnUpdatePeriods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePeriodsActionPerformed(evt);
            }
        });

        btnDeletePeriods.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Eliminar.png"))); // NOI18N
        btnDeletePeriods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePeriodsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddPeriods, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdatePeriods, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeletePeriods, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPeriods, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdatePeriods, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletePeriods, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Periodos", jPanel4);

        tblCandidate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblCandidate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Número de identificación", "Nombre", "Partido político", "Imagen"
            }
        ));
        tblCandidate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCandidateMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCandidate);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Candidatos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N

        lblIdentificación1.setText("Cedula:");

        lblNombre1.setText("Nombre:");

        lblPartidoPolítico1.setText("Patido Politico:");

        lblRuta1.setText("Imagen:");

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPartidoPolítico1)
                    .addComponent(lblIdentificación1)
                    .addComponent(lblNombre1)
                    .addComponent(lblRuta1))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtImage, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(txtNameCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdNumberCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPoliticParty, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificación1)
                    .addComponent(txtIdNumberCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre1))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPartidoPolítico1)
                    .addComponent(txtPoliticParty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRuta1)
                    .addComponent(jButton1))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        btnAddCandidate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/AgregarUsuario.png"))); // NOI18N
        btnAddCandidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCandidateActionPerformed(evt);
            }
        });

        btnUpdateCandidate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Editar.png"))); // NOI18N
        btnUpdateCandidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCandidateActionPerformed(evt);
            }
        });

        btnDeleteCandidate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Eliminar.png"))); // NOI18N
        btnDeleteCandidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCandidateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnUpdateCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar candidatos", jPanel2);

        lblExit5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblExit5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit5.setText("X");
        lblExit5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblExit5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExit5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExit5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnBtnExitLayout = new javax.swing.GroupLayout(pnBtnExit);
        pnBtnExit.setLayout(pnBtnExitLayout);
        pnBtnExitLayout.setHorizontalGroup(
            pnBtnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnBtnExitLayout.setVerticalGroup(
            pnBtnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCandidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCandidateActionPerformed
        cc.addCandidate(txtIdNumberCandidate, txtNameCandidate, txtPoliticParty, txtImage);
        listCandidates();
    }//GEN-LAST:event_btnAddCandidateActionPerformed

    private void btnUpdateCandidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCandidateActionPerformed
        cc.updateCandidate(txtIdNumberCandidate, txtNameCandidate, txtPoliticParty, txtImage);
        listCandidates();
        clearFiledsCandidates();
    }//GEN-LAST:event_btnUpdateCandidateActionPerformed

    private void btnDeleteCandidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCandidateActionPerformed
        cc.deleteCandidate();
        listCandidates();
    }//GEN-LAST:event_btnDeleteCandidateActionPerformed

    private void tblCandidateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCandidateMouseClicked
        cc.selectedRow(tblCandidate, txtIdNumberCandidate, txtNameCandidate, txtPoliticParty, txtImage);
        int selectedRow = tblCandidate.getSelectedRow();
        String imagePath = tblCandidate.getValueAt(selectedRow, 4).toString();
        mostrarImagen(imagePath);
    }//GEN-LAST:event_tblCandidateMouseClicked

    private void txtKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeyActionPerformed

    private void txtLimitDatePeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLimitDatePeriodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLimitDatePeriodActionPerformed

    private void btnAddVoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVoterActionPerformed

        vt.addUserForAdmin(txtIdNumberVoter, txtNameVoter, txtEmailVoter, txtAgeVoter, txtTelephoneVoter, txtKey);
        listVoters();
    }//GEN-LAST:event_btnAddVoterActionPerformed

    private void btnUpdateVoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateVoterActionPerformed
        vt.updateUser(tblVoters, txtIdNumberVoter, txtNameVoter, txtEmailVoter, txtAgeVoter, txtTelephoneVoter, txtKey);
        listVoters();
        clearFiledsVoters();
    }//GEN-LAST:event_btnUpdateVoterActionPerformed

    private void btnDeleteVoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVoterActionPerformed
        vt.deleteUser();
        listVoters();
    }//GEN-LAST:event_btnDeleteVoterActionPerformed

    private void tblVotersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVotersMouseClicked
        vt.selectedRow(tblVoters, txtIdNumberVoter, txtNameVoter, txtEmailVoter, txtAgeVoter, txtTelephoneVoter, txtKey);
    }//GEN-LAST:event_tblVotersMouseClicked

    private void btnGenerateKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateKeyActionPerformed
        generateKey();
    }//GEN-LAST:event_btnGenerateKeyActionPerformed

    private void btnAddPeriodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPeriodsActionPerformed
        pr.addPeriod(txtStartDatePeriods, txtFinishDatePeriods, txtStatusPeriod);
        listPeriods();
    }//GEN-LAST:event_btnAddPeriodsActionPerformed

    private void btnUpdatePeriodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePeriodsActionPerformed
        pr.updatePeriod(txtStartDatePeriods, txtFinishDatePeriods, txtStatusPeriod);
        listPeriods();
        clearFiledsPeriods();
    }//GEN-LAST:event_btnUpdatePeriodsActionPerformed

    private void btnDeletePeriodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePeriodsActionPerformed
        pr.deletePeriod();
        listPeriods();
    }//GEN-LAST:event_btnDeletePeriodsActionPerformed

    private void tblPeriodsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPeriodsMouseClicked
        pr.selectedRow(tblPeriods, txtStartDatePeriods, txtFinishDatePeriods, txtStatusPeriod);
    }//GEN-LAST:event_tblPeriodsMouseClicked

    private void lblExit5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit5MouseClicked
        dashboard i = new dashboard();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblExit5MouseClicked

    private void lblExit5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit5MouseEntered
        pnBtnExit.setBackground(Color.red);
        lblExit5.setForeground(Color.white);
    }//GEN-LAST:event_lblExit5MouseEntered

    private void lblExit5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit5MouseExited
        pnBtnExit.setBackground(Color.white);
        lblExit5.setForeground(Color.black);
    }//GEN-LAST:event_lblExit5MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("C:\\Users\\Bravo\\Documents\\FinalProject_DEU\\FinalProject\\src\\View\\Images"));

        int result = fileChooser.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            String imageName = "/View/Images/" + fileChooser.getSelectedFile().getName();
            txtImage.setText(imageName);
            String imagePath = fileChooser.getSelectedFile().getPath();
            if (!imagePath.startsWith("C:\\Users\\Bravo\\Documents\\FinalProject_DEU\\FinalProject\\src\\View\\Images")) {
                txtImage.setText(imagePath);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mostrarImagen(String imagePath) {
        try {
            File imageFile = new File(imagePath);
            if (imageFile.exists() && !imageFile.isDirectory()) {
                ImageIcon imageIcon = new ImageIcon(imagePath);
                lblImage.setIcon(imageIcon);
            } else {
                ImageIcon imageIcon = new ImageIcon(getClass().getResource(imagePath));
                lblImage.setIcon(imageIcon);
            }

            lblImage.repaint();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCandidate;
    private javax.swing.JButton btnAddPeriods;
    private javax.swing.JButton btnAddVoter;
    private javax.swing.JButton btnDeleteCandidate;
    private javax.swing.JButton btnDeletePeriods;
    private javax.swing.JButton btnDeleteVoter;
    private javax.swing.JButton btnGenerateKey;
    private javax.swing.JButton btnUpdateCandidate;
    private javax.swing.JButton btnUpdatePeriods;
    private javax.swing.JButton btnUpdateVoter;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblExit5;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFinish_date;
    private javax.swing.JLabel lblIdentificación1;
    private javax.swing.JLabel lblIdentificación2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblPartidoPolítico1;
    private javax.swing.JLabel lblRuta1;
    private javax.swing.JLabel lblRuta2;
    private javax.swing.JLabel lblStart_date;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnBtnExit;
    private javax.swing.JTable tblCandidate;
    private javax.swing.JTable tblPeriods;
    private javax.swing.JTable tblVoters;
    private javax.swing.JTextField txtAgeVoter;
    private javax.swing.JTextField txtEmailVoter;
    private javax.swing.JTextField txtFinishDatePeriods;
    private javax.swing.JTextField txtIdNumberCandidate;
    private javax.swing.JTextField txtIdNumberVoter;
    private javax.swing.JTextField txtImage;
    private javax.swing.JTextField txtKey;
    private javax.swing.JTextField txtLimitDatePeriod;
    private javax.swing.JTextField txtNameCandidate;
    private javax.swing.JTextField txtNameVoter;
    private javax.swing.JTextField txtPoliticParty;
    private javax.swing.JTextField txtStartDatePeriods;
    private javax.swing.JTextField txtStatusPeriod;
    private javax.swing.JTextField txtTelephoneVoter;
    // End of variables declaration//GEN-END:variables
}
