/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.CtrlCandidates;
import Controller.CtrlPeriods;
import Controller.CtrlUsers;

/**
 *
 * @author Eithel
 */
public class adminFrame extends javax.swing.JFrame {
     CtrlCandidates cc = new CtrlCandidates();
     CtrlUsers vt = new CtrlUsers();
     CtrlPeriods pr = new CtrlPeriods();

    /**
     * Creates new form adminFrame
     */
    public adminFrame() {
        initComponents();
        setLocationRelativeTo(null);
        listPeriods();
        this.listCandidates();
        this.listVoters();
        generateKey();
        this.pr.getActivePeriods(txt_fecha_limite);
    }
     public void listPeriods(){
        pr.loadDataPeriods(tblPeriods);
    }
    public void clearFiledsPeriods(){
       pr.addPeriod(txt_start_date, txt_finish_date, txt_status);
    }
    public void listVoters() {
        vt.loadDataUsers(tblVoters);
    }

    public void clearFiledsVoters() {
        vt.clearFields(txt_numero_identificacion, txt_nombre, txt_email, txt_telefono, txt_clave);
    }

    public void generateKey() {
        String randomKey = vt.generateRandomKey();
        txt_clave.setText(randomKey);
    }
     public void listCandidates(){
        cc.loadDataCandidates(tblCandidate);
    }
    
    public void clearFiledsCandidates(){
        cc.clearFields(txt_numero_identificacion, txt_nombre, txt_partido_politico, txt_imagen);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblIdentificación1 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblPartidoPolítico1 = new javax.swing.JLabel();
        lblRuta1 = new javax.swing.JLabel();
        txt_numero_identificacion1 = new javax.swing.JTextField();
        txt_nombre1 = new javax.swing.JTextField();
        txt_partido_politico1 = new javax.swing.JTextField();
        txt_imagen1 = new javax.swing.JTextField();
        btnAddCandidate = new javax.swing.JButton();
        btnUpdateCandidate = new javax.swing.JButton();
        btnDeleteCandidate = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCandidate = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblIdentificación2 = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblRuta2 = new javax.swing.JLabel();
        txt_numero_identificacion2 = new javax.swing.JTextField();
        txt_nombre2 = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        lblClave = new javax.swing.JLabel();
        txt_clave = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        txt_fecha_limite = new javax.swing.JTextField();
        btnAddVoter = new javax.swing.JButton();
        btnUpdateVoter = new javax.swing.JButton();
        btnDeleteVoter = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVoters = new javax.swing.JTable();
        btnSalir2 = new javax.swing.JButton();
        btnGenerateKey = new javax.swing.JButton();
        lblAge = new javax.swing.JLabel();
        txt_Age = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lblStart_date = new javax.swing.JLabel();
        lblFinish_date = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txt_start_date = new javax.swing.JTextField();
        txt_status = new javax.swing.JTextField();
        txt_finish_date = new javax.swing.JTextField();
        btnAddPeriods = new javax.swing.JButton();
        btnUpdatePeriods = new javax.swing.JButton();
        btnDeletePeriods = new javax.swing.JButton();
        btnSalir3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPeriods = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIdentificación1.setText("Ingrese el número de identificación:");

        lblNombre1.setText("Ingrese su nombre:");

        lblPartidoPolítico1.setText("Ingrese el nombre del partido político:");

        lblRuta1.setText("La ruta de la imagen:");

        btnAddCandidate.setText("Agregar");
        btnAddCandidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCandidateActionPerformed(evt);
            }
        });

        btnUpdateCandidate.setText("Modifcar");
        btnUpdateCandidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCandidateActionPerformed(evt);
            }
        });

        btnDeleteCandidate.setText("Eliminar");
        btnDeleteCandidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCandidateActionPerformed(evt);
            }
        });

        btnSalir1.setText("Salir");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        tblCandidate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Número de identificación", "Nombre", "Partido político", "Imagen"
            }
        ));
        tblCandidate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCandidateMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCandidate);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdentificación1)
                            .addComponent(lblRuta1)
                            .addComponent(lblPartidoPolítico1)
                            .addComponent(lblNombre1))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_partido_politico1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_numero_identificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnAddCandidate)
                        .addGap(88, 88, 88)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalir1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnUpdateCandidate)
                                .addGap(92, 92, 92)
                                .addComponent(btnDeleteCandidate)))))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdentificación1)
                            .addComponent(txt_numero_identificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre1)
                            .addComponent(txt_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPartidoPolítico1)
                            .addComponent(txt_partido_politico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRuta1)
                            .addComponent(txt_imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddCandidate)
                            .addComponent(btnUpdateCandidate)
                            .addComponent(btnDeleteCandidate)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir1)
                .addGap(67, 67, 67))
        );

        jTabbedPane1.addTab("Registrar candidatos", jPanel2);

        lblIdentificación2.setText("Ingrese el número de identificación:");

        lblNombre2.setText("Ingrese su nombre:");

        lblEmail.setText("Ingrese su correo electronico:");

        lblRuta2.setText("Ingrese su número de telefono:");

        lblClave.setText("Esta es su clave:");

        txt_clave.setEditable(false);
        txt_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_claveActionPerformed(evt);
            }
        });

        lblFecha.setText("Esta es su fecha para votar:");

        txt_fecha_limite.setEditable(false);
        txt_fecha_limite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fecha_limiteActionPerformed(evt);
            }
        });

        btnAddVoter.setText("Agregar");
        btnAddVoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVoterActionPerformed(evt);
            }
        });

        btnUpdateVoter.setText("Modificar");
        btnUpdateVoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateVoterActionPerformed(evt);
            }
        });

        btnDeleteVoter.setText("Eliminar");
        btnDeleteVoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVoterActionPerformed(evt);
            }
        });

        tblVoters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Número de identificación", "Nombre", "Email", "Edad", "Teléfono", "Clave", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVoters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVotersMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblVoters);

        btnSalir2.setText("Salir");
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });

        btnGenerateKey.setText("Generar");
        btnGenerateKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateKeyActionPerformed(evt);
            }
        });

        lblAge.setText("Ingrese su edad:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_fecha_limite, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdentificación2)
                                    .addComponent(lblRuta2)
                                    .addComponent(lblEmail)
                                    .addComponent(lblNombre2)
                                    .addComponent(lblAge))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_numero_identificacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lblClave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGenerateKey)
                                    .addComponent(txt_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btnAddVoter)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalir2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnUpdateVoter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDeleteVoter)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1015, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdentificación2)
                            .addComponent(txt_numero_identificacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre2)
                            .addComponent(txt_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRuta2)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(txt_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClave)
                            .addComponent(txt_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGenerateKey)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFecha)
                            .addComponent(txt_fecha_limite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateVoter)
                    .addComponent(btnDeleteVoter)
                    .addComponent(btnAddVoter))
                .addGap(30, 30, 30)
                .addComponent(btnSalir2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar votantes", jPanel3);

        lblStart_date.setText("Fecha de inicio:");

        lblFinish_date.setText("Fecha de finalización:");

        lblStatus.setText("Estado:");

        btnAddPeriods.setText("Agregar");
        btnAddPeriods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPeriodsActionPerformed(evt);
            }
        });

        btnUpdatePeriods.setText("Modificar");
        btnUpdatePeriods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePeriodsActionPerformed(evt);
            }
        });

        btnDeletePeriods.setText("Eliminar");
        btnDeletePeriods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePeriodsActionPerformed(evt);
            }
        });

        btnSalir3.setText("Salir");
        btnSalir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir3ActionPerformed(evt);
            }
        });

        tblPeriods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Fecha de inicio", "Fecha de finalización", "Estado"
            }
        ));
        tblPeriods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPeriodsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblPeriods);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStart_date)
                            .addComponent(lblStatus)
                            .addComponent(lblFinish_date))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_finish_date, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_start_date, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAddPeriods)
                        .addGap(52, 52, 52)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalir3)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnUpdatePeriods)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeletePeriods)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(610, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStart_date)
                            .addComponent(txt_start_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFinish_date)
                            .addComponent(txt_finish_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStatus)
                            .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddPeriods)
                            .addComponent(btnUpdatePeriods)
                            .addComponent(btnDeletePeriods))
                        .addGap(43, 43, 43)
                        .addComponent(btnSalir3)))
                .addGap(92, 92, 92))
        );

        jTabbedPane1.addTab("Agregar Periodos", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1501, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCandidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCandidateActionPerformed
        cc.addCandidate(txt_numero_identificacion, txt_nombre, txt_partido_politico, txt_imagen);
        listCandidates();
    }//GEN-LAST:event_btnAddCandidateActionPerformed

    private void btnUpdateCandidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCandidateActionPerformed
        cc.updateCandidate(txt_numero_identificacion, txt_nombre, txt_partido_politico, txt_imagen);
        listCandidates();
        clearFiledsCandidates();
    }//GEN-LAST:event_btnUpdateCandidateActionPerformed

    private void btnDeleteCandidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCandidateActionPerformed
        cc.deleteCandidate();
        listCandidates();
    }//GEN-LAST:event_btnDeleteCandidateActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        Interface ventanaPrincipal= new Interface();
        ventanaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void tblCandidateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCandidateMouseClicked
        cc.selectedRow(tblCandidate,txt_numero_identificacion, txt_nombre, txt_partido_politico, txt_imagen);
    }//GEN-LAST:event_tblCandidateMouseClicked

    private void txt_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_claveActionPerformed

    private void txt_fecha_limiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fecha_limiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fecha_limiteActionPerformed

    private void btnAddVoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVoterActionPerformed

        vt.addUser(txt_numero_identificacion, txt_nombre, txt_email, txt_Age, txt_telefono, txt_clave, this);
        listVoters();
    }//GEN-LAST:event_btnAddVoterActionPerformed

    private void btnUpdateVoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateVoterActionPerformed
        vt.updateUser(txt_numero_identificacion, txt_nombre, txt_email, txt_Age, txt_telefono, txt_clave);
        listVoters();
        clearFiledsVoters();
    }//GEN-LAST:event_btnUpdateVoterActionPerformed

    private void btnDeleteVoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVoterActionPerformed
        vt.deleteUser();
        listVoters();
    }//GEN-LAST:event_btnDeleteVoterActionPerformed

    private void tblVotersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVotersMouseClicked
        vt.selectedRow(tblVoters, txt_numero_identificacion, txt_nombre, txt_email, txt_Age, txt_telefono, txt_clave);
    }//GEN-LAST:event_tblVotersMouseClicked

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        Interface ventanaPrincipal = new Interface();
        ventanaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalir2ActionPerformed

    private void btnGenerateKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateKeyActionPerformed
        generateKey();
    }//GEN-LAST:event_btnGenerateKeyActionPerformed

    private void btnAddPeriodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPeriodsActionPerformed
        pr.addPeriod(txt_start_date, txt_finish_date, txt_status);
        listPeriods();
    }//GEN-LAST:event_btnAddPeriodsActionPerformed

    private void btnUpdatePeriodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePeriodsActionPerformed
        pr.addPeriod(txt_start_date, txt_finish_date, txt_status);
        listPeriods();
        clearFiledsPeriods();
    }//GEN-LAST:event_btnUpdatePeriodsActionPerformed

    private void btnDeletePeriodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePeriodsActionPerformed
        pr.deletePeriod();
        listPeriods();
    }//GEN-LAST:event_btnDeletePeriodsActionPerformed

    private void btnSalir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir3ActionPerformed
        Interface ventanaPrincipal= new Interface();
        ventanaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalir3ActionPerformed

    private void tblPeriodsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPeriodsMouseClicked
        pr.selectedRow(tblPeriods, txt_start_date, txt_finish_date, txt_status);
    }//GEN-LAST:event_tblPeriodsMouseClicked

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCandidate;
    private javax.swing.JButton btnAddPeriods;
    private javax.swing.JButton btnAddVoter;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnDeleteCandidate;
    private javax.swing.JButton btnDeletePeriods;
    private javax.swing.JButton btnDeleteVoter;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerateKey;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JButton btnSalir3;
    private javax.swing.JButton btnUpdateCandidate;
    private javax.swing.JButton btnUpdatePeriods;
    private javax.swing.JButton btnUpdateVoter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFinish_date;
    private javax.swing.JLabel lblIdentificación;
    private javax.swing.JLabel lblIdentificación1;
    private javax.swing.JLabel lblIdentificación2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblPartidoPolítico;
    private javax.swing.JLabel lblPartidoPolítico1;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JLabel lblRuta1;
    private javax.swing.JLabel lblRuta2;
    private javax.swing.JLabel lblStart_date;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblCandidate;
    private javax.swing.JTable tblCandidates;
    private javax.swing.JTable tblPeriods;
    private javax.swing.JTable tblVoters;
    private javax.swing.JTextField txt_Age;
    private javax.swing.JTextField txt_clave;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fecha_limite;
    private javax.swing.JTextField txt_finish_date;
    private javax.swing.JTextField txt_imagen;
    private javax.swing.JTextField txt_imagen1;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombre1;
    private javax.swing.JTextField txt_nombre2;
    private javax.swing.JTextField txt_numero_identificacion;
    private javax.swing.JTextField txt_numero_identificacion1;
    private javax.swing.JTextField txt_numero_identificacion2;
    private javax.swing.JTextField txt_partido_politico;
    private javax.swing.JTextField txt_partido_politico1;
    private javax.swing.JTextField txt_start_date;
    private javax.swing.JTextField txt_status;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
